### ISSUE TITLE
Add a Note that Dict.get is O(n)

### ISSUE THREAD

**Issue by alexanderkiel** [jjant/elm-dict#1]
You have a nice implementation of a Dict here. But others should know from the start that `Dict.get` is O(n) so that they can decide whether they can use it.

**Comment by jjant** [comment]
Hey there!

Yes, I think you're right, that should be in the readme. One caveat is that the Dict is not `O(n)` in the number of elements, but on the number of **insertions**.

**Comment by alexanderkiel** [comment]
Hi! Yes the `n` is the number of insertions.

**Comment by jjant** [comment]
Resolved in #2
